/run/initialize
/tracking/verbose 0

/control/getEnv a
/control/getEnv b

/random/setSeeds {a} {b}

/process/list
/run/printProgress 1000

/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/halfx 3.327 m
/gps/pos/halfy 4.675315 m
/gps/pos/halfz 2.818 m
/gps/pos/centre 0.5 -1.2 1 m 

/gps/energy 0 MeV
/gps/ang/type iso
/gps/particle ion
/gps/ion 92 238 0 0
/gps/pos/confine LabFloorWall

/filename/setFilename DTFridgelab_0.root

/run/beamOn 700000 #geom40
